package com.example.kudu_kulinerbandung;

import java.util.ArrayList;

public class DataMakanan {

    public static String[][] data = new String[][]{
            {"Seblak","Mulai dari 12,000 IDR","Jl. Buah Batu No.163, Turangga, Lengkong, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304042222/1-1-SeblakJebred-By-duniakulinerbdg.jpg", "Belum ke Bandung jika kamu belum mencoba makan seblak. Makanan khas Bandung yang terbuat dari kerupuk basah ini memiliki rasa yang khas karena dibuat dari bumbu rempah dan memiliki isian yang mengenyangkan seperti sayur, daging dan telur.\n\n Ada beberapa tempat asyik untuk merasakan seblak, namun salah satu yang layak direkomendasikan adalah Seblak Jebred yang memiliki tambahan ceker di isiannya, plus tahu krispi, sosis dan kikil. Supaya semakin nyam-nyam, naikkan versi pedasnya, ya! Harganya juga cukup ramah di kantong, lho!"},
            {"Nasi Tutug Oncom","8,000 IDR - 25,000 IDR","Jl. Macan, Burangrang, Lengkong, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304042727/2-1-TutugOncom-By-mod_eka.jpg","Dari namanya, kamu sudah bisa menebak seperti apa komposisi kuliner ini. Nasi yang ditumbuk dan dicampur oncom, ditambah dengan lauk pauk yang sesuai dengan selera, kamu bisa mendapatkan sensasi rasa yang aduhai.\n\n Namun, pertanyaan besarnya, di mana tempat yang menyajikan nasi tutug oncom paling mantab? Ada banyak pendapat, dan semuanya memiliki cita rasanya sendiri. Kami merekomendasikan Nasi Tutug Oncom Bi Kokom di daerah Lengkong, yang tidak hanya memiliki menawarkan rasa yang pas, tapi juga fasilitas yang memadai."},
            {"Nasi Timbel", "Mulai dari 4,000 IDR","Jl. Bawean Pav. 3, Bandung, Merdeka, Sumur Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304043232/3-1-NasiTimbel-By-foodgallerybdg.jpg", "Disebut tersembunyi karena nasinya dibungkus daun pisang. Setelah dibuka, kamu bisa mendapati nasi putih hangat dengan aroma yang khas dan bisa menikmatinya dengan ditemani daging atau ikan, tahu, tempe serta sambal dan lalapan.\n\n Ingin mendapatkan rasa otentik dari makanan khas Bandung ini, langsung saja menuju ke nasi timbel Bawean, spot legendaris yang sudah berdiri sejak 1985. Selain pilihan lauknya yang melimpah, kamu juga bisa memilih varian nasi timbelnya, nasi timbel putih dan merah. Wow!"},
            {"Karedok","Mulai 10,000 IDR","Jl. Cihapit No.6, Cihapit, Bandung Wetan, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304043838/4-1-Karedok-By-saungpengkolanlembang.jpg", "Tertarik mengkonsumsi makanan yang bergizi dan menyehatkan di Bandung, silakan langsung mencoba karedok. Mulai dari bahan, cara pengolahan dan penyajian, semuanya berakhir dengan kesegaran. Untuk menambah rasa, kamu harus meminta diolah dengan tingkat pedas sedikit di atas rata-rata.\n\n Salah satu penjual karedok yang cukup favorit di kota Bandung adalah Warung Cihapit Bu Siti. Selain karedok, kamu juga bisa mencoba lotek, pecel dan gado-gado. Dijamin semuanya menyehatkan, lho!"},
            {"Mie Kocok","Mulai dari 23,000 IDR","Jl. Kyai Haji Ahmad Dahlan No. 67, Turangga, Lengkong, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304044747/5-1-MieKocok-By-eatineraryid.jpg", "Bagi kamu yang tertarik menikmati sajian yang memanjakan lidah, Mie Kocong Mang Dadeng bisa menjadi alternatif yang pas. Rasanya nendang, pun demikian dengan isian di setiap porsi mie kocok yang disajikan.\n\n Bukan hal yang mengejutkan karena kabarnya ada bumbu spesial, yang terdiri dari 27 macam bumbu rempah yang menjadikan rasa mie kocok Mang Dadeng begitu ngehits di kalangan pecinta kuliner tradisional. Kaldunya juga cukup berasa, sementara isiannya, seperti mie kuning gepeng, potongan kikil dan sum sum, serta daun seledri dan bawang goreng untuk menambah rasa, membuat kamu ingin terus nambah dan nambah."},
            {"Surabi","Mulai dari 2,000 IDR","Jl. Cihapit, Cihapit, Bandung, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304045454/6-1-SurabiCihapit-By-kulinerakut.jpg", "Surabi menjadi salah satu camilan paling ngehits di Bandung. Beragam rasa, topping dan tampilan yang imut menjadi alasan mengapa jajanan tradisional ini banyak diburu para pendatang dan kaum urban Bandung.\n\n Salah satu pioner surabi di Bandung adalah Surabi Cihapit, yang berdiri sejak 1991. Menu yang paling terkenal adalah surabi oncom, namun varian lain juga layak dicoba. Dijamin ketagihan, lho!"},
            {"Ulukutek Leunca","Mulai dari 10,000 IDR","Warung Ibu Imas, Jl. Balonggede No. 38, Balonggede, Regol, Balonggede, Regol, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304040303/7-1-UlukutekLeunca-By-mamanivla.jpg","Kamu akan terkejut dengan kandungan gizi dalam makanan khas Bandung nan tradisional ini. Mulai dari kandungan kalori, vitamin, karbohidrat hingga senyawa yang dibutuhkan oleh tubuh terdapat dalam makanan ini.\n\n Luar biasanya lagi, kamu bisa menikmatinya kapan pun karena rasanya yang gurih, renyah, sedikit pahit dan pedas. Penikmatnya dijamin akan mendapatkan sensasi tersendiri mengkonsumsi kuliner ini. Dalam seporsi ulukutek leunca, juga ada tambahan oncom, yang akan menambah cita rasa yang mengesankan. Selain itu, kamu bisa mudah menemukan sajian ini di banyak tempat."},
            {"Gehu Jeletot","2,000 IDR per buah","JL. Jupiter Raya, Blok F2 No. 25, Margahayu Barat, Sekejati, Sekejati, Buahbatu, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304040808/8-1-GehuJeletot-By-ameliasepthi.jpg", "Bagi pencari rasa pedas, kuliner Gehu Jeletot bisa jadi alternatif yang pas. Camilan baru di kota Bandung ini banyak menjadi buruan karena rasa pedas, gurih dan menyenangkan. Selain taburan sayuran di dalam tahunya, seperti irisan wortel dan sayur kol, ada juga irisan daging sapi untuk menambah cita rasa.\n\n Gehu Hot Jeletot menjadi tempat yang tepat bagi kamu yang menginginkan makanan khas Bandung ini. Harganya memang relatif lebih mahal dibanding produk sejenis lainnya di Bandung, namun kualitas rasanya cukup berbeda."},
            {"Bandros","8,000 IDR - 45,000 IDR","Jl. Cisangkuy No.56, Citarum, Bandung Wetan, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304041414/9-1-Bandros-By-lets.go_.eat_.jpg", "Salah satu camilan tradisional kota Bandung yang paling diminati adalah bandros. Kue dari campuran tepung beras dan santan ini berbentuk seperti pukis dengan rasa gurih. Ada taburan gula pasir untuk menambah cita rasa.\n\n Kini variannya sudah beragam. Salah satu yang menyajikan dengan cara unik adalah bandros Cowboy Cisangkuy. Ada beragam rasa ditawarkan, mulai dari green tea, keju, coklat hingga beberapa merek coklat kenamaan. Di sini, kamu tetap bisa mendapatkan bandros versi original, kok!"},
            {"Colenak", "10,000 IDR per bungkus","Jalan Ahmad Yani No. 733, Cicaheum, Kiaracondong, Padasuka, Cibeunying Kidul, Kota Bandung, Jawa Barat", "https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304041919/10-1-Colenak-By-lets.go_.eat_.jpg", "Tidak sedikit yang mengenalnya sebagai tape bakar, namun apa pun itu kualitas rasanya sudah mendunia. Bayangkan tape singkong yang dibakar dan dicocol pada gula merah yang dipanaskan bersama parutan kelapa, bikin ngiler, kan?\n\n Salah satu tempat mendapatkan makanan khas Bandung ini adalah di Colenak Murdi Putra, yang konon sudah berdiri sejak 1930. Kamu harus mencicipi yang ini saat liburan ke Bandung, ya!"},
            {"Pisang Bollen","Mulai dari 24,000 IDR","Jalan Haji Akbar No.4, Pasir Kaliki, Cicendo, Pasir Kaliki, Cicendo, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304042525/11-1-Kartikasari-By-Kartikasari.jpg","Tidak jarang mereka yang bepergian ke Bandung membawakan oleh-oleh camilan ini untuk sanak keluarga dan sahabat di kampung halaman. Lumrah karena pisang bollen Kartika Sari, tidak hanya enak, tapi juga meninggalkan kesan yang memesona. Sekarang banyak pilihan rasa, mulai dari kacang hijau hingga peuyeum. Kamu suka yang mana?"},
            {"Peyeum","15,000 IDR per kilogram","Jalan Bandung-Cianjur, Kampung Cimerang, Desa Citatah, Cipatat, Kabupaten Bandung Barat, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304045959/12-1-PeuYeum-By-omamuda.jpg","Inilah salah satu makanan khas Bandung yang begitu identik dengan Kota Kembang. Bukan sekadar tape singkong, peuyeum merupakan tape dengan kadar air yang jauh lebih sedikit, yang membuatnya bisa bertahan jauh lebih lama.\n\n Serunya, peuyeum bisa menjadi makanan yang disantap langsung, atau menjadi bahan dasar untuk olahan camilan kesukaan kamu. Banyak tempat untuk bisa mendapatkan peuyeum. Rekomendasi kami, langsung ke sentranya di Desa Citatah."},
            {"Gepuk","Mulai dari 18,000","Jalan Pasir Kaliki 96, Cicendo, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304040202/13-1-GepukNyOng-By-gepuknyong.jpg","Makanan ini bukan untuk kamu yang mengusung semangat vegan. Maklum, bahan dasarnya saja daging sapi. Cara menyantapnya juga khas, dengan nasi hangat dan sambal. Ingin varian lain, kamu bisa memilih sejumlah alternatif termasuk di antaranya beef salty, beef less sugar hingga chicken spicy.\n\n Tempat terbaik mendapatkan kuliner ini adalah di Gepuk Ny. Ong, yang interior restorannya yang dipenuhi barang antik dan Instagenik."},
            {"Wajit","15,000 IDR per bungkus","Jalan Raya Radio No.1, Cililin, Kabupaten Bandung Barat, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304040505/14-1-WajitCililin-By-hanaka_shop.jpg","Di sejumlah wilayah di Bandung ternyata memiliki kuliner yang khas. Di Bandung Barat misalnya, yang identik dengan Wajit Cililin. Camilan yang terbuat dari beras ketan, gula aren, kelapa dan vanili ini cukup populer untuk dijadikan sebagai oleh-oleh.\n\n Di sentra pembuatan wajit Cililin, Bandung Barat, kamu tidak hanya bisa menikmatinya, tapi juga melihat pembuatannya. Tertarik ke sana?"},
            {"Es Goyobod","Mulai dari 3,000 IDR","Jalan Kliningan B 9, RT01/ RW05, Turangga, Lengkong, Turangga, Lengkong, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304041010/15-1-EsGoyobodKliningan-By-elia_budiantini.jpg","Mulai gerah dan kepanasan dengan udara Bandung yang kurang bersahabat? Redakan dengan menikmati seporsi es goyobod yang menyegarkan. Minuman dingin khas Sunda ini memang menjadi ‘obat’ yang tepat untuk mengatasi dahaga kamu.\n\n Es goyobod Kliningan berisi adonan sagu aren yang kenyal dengan kuah santan, susu kental manis dan serutan es. Materi pelengkapnya mulai dari alpukat, roti tawar, peuyeum, pacar Cina, kolang-kaling hingga kelapa muda. Dengan harga yang sangat terjangkau, dijamin kamu akan nambah dan nambah lagi!"},
            {"Yogurt","Mulai dari 20,000 IDR","Jl. Cisangkuy No.66, Citarum, Bandung Wetan, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304041212/16-1-YogurtCisangkuy-By-duniakulinerbdg.jpg","Salah satu yang bisa melegakan rasa dahaga kamu adalah di yoghurt.Berdiri sejak 1976, Yoghurt Cisangkuy termasuk salah satu kuliner khas Bandung yang melegenda. Bukan hanya menawarkan tempat nongkrong yang cozy, tapi juga menyajikan minuman menyehatkan dan menyegarkan. Selain itu, ada juga olahan kuliner lain yang layak kamu coba untuk memperpanjang masa istirahat di tempat ini."},
            {"Cuanki","17,000 IDR per porsi","Jalan Serayu No.2, Cihapit, Bandung Wetan, Kota Bandung, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304041515/17-1-CuankiSerayu-By-dailyculinary_.jpg","Sajiannya mirip bakso Malang. Dalam satu porsi cuanki terdiri dari aci, siomay, bakso, pangsit rebus, pangsit goreng dan bakso goreng. Bedanya, mi yang digunakan bukan mi kuning. Dengan tambahan seledri dan daun bawang, Cuanki juga lebih gurih dan bening.\n\n Banyak tempat untuk bisa menikmati cuanki, mengingat pada awalnya kuliner ini ditawarkan oleh penjualnya dengan berkeliling. Namun kini ada satu spot yang cukup populer bagi pecinta kuliner, yaitu Cuanki Serayu, yang sudah berdiri sejak 1990."},
            {"Tahu Susu Lembang","25,000 IDR per bungkus","Jl. Raya Lembang No.177, Jayagiri, Lembang, Kabupaten Bandung Barat, Jawa Barat","https://sgp1.digitaloceanspaces.com/tz-mag-id/wp-content/uploads/2018/04/030304041818/18-1-TahuSusuLembang-By-virnasari.jpg","Berkunjung ke Lembang, pulangnya pun harus membawa Tahu Susu Lembang. Tidak hanya lezat, kuliner dari Lembang ini diklaim juga menyehatkan, lho!\n\n Kualitas tahunya juga berbeda dari kebanyakan, karena terkenal lembut. Selain tahu susu, kamu juga bisa mendapatkan alternatif oleh-oleh lain untuk dibawa pulang."}
    };

    public static ArrayList<Makanan> getListData(){
        ArrayList<Makanan> list = new ArrayList<>();
        for(String[] aData : data){
            Makanan makanan = new Makanan();
            makanan.setNama(aData[0]);
            makanan.setHarga(aData[1]);
            makanan.setLokasi(aData[2]);
            makanan.setPhoto(aData[3]);
            makanan.setDesk(aData[4]);

            list.add(makanan);
        }

        return list;
    }
}
